
[functions.create-checkout-session]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.whatsapp-connection]
verify_jwt = true

[functions.evolution-integration]
verify_jwt = true
